export const FETCH_IMAGES = "FETCH_IMAGES";
export const FETCH_IMAGE_DETAIL = "FETCH_IMAGE_DETAIL";
export const ADD_IMAGE = "ADD_IMAGE";
export const UPLOAD_ORIGINALIMAGE = "UPLOAD_ORIGINALIMAGE";
export const REMOVE_ORIGINALIMAGE = "REMOVE_ORIGINALIMAGE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
